title = System Looting
description = Competitive team-based survival with crafting, abilities, and asymmetric monster master.
allowed_mapgens = singlenode
min_minetest_version = 5.0
map_persistent = true
author = SodoMita
release = 2
time_speed = 0
