name = sl_weapons
description = Ranged arsenal, weapon pads, sentry turrets, corpses & the Grapple Lash (WEAPONS_SPEC)
author = SodoMita
depends = sl_modebase, default, sl_texgen
optional_depends = sl_gui
min_minetest_version = 5.0
